name: "Artillery load testing action"
author: Artillery
description: "Load testing of your application at scale."

inputs:
  test:
    required: true
    description: "A test script path."

  target:
    description: "Set or override the target URL for the tests"

  output:
    description: "Save the test run report to the given path"
    default: "./report.json"

  config:
    description: "A path to the shared configuration file"

  insecure:
    description: "Turn off TLS validation during the test run"

  quiet:
    description: "Run in quiet mode"

outputs:
  report:
    description: "A path to the generated report JSON file"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: zap
  color: gray-dark
