language: node_js
node_js:
  - "10.14.1"
sudo: false
before_script:
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - export PATH=$PATH:/tmp/local/bin
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - jq
    - gcc-4.8
    - g++-4.8
notifications:
  email:
    on_success: never
