version: 0.2

phases:
  install:
    commands:
      - npm install -g artillery@latest
  pre_build:
    commands:
      - mkdir reports
  build:
    commands:
      - artillery run --output reports/report.json tests/performance/socket-io.yml

artifacts:
  files:
    - 'reports/*'
  name: artifacts/$CODEBUILD_BUILD_NUMBER
