artillery:
  image:
    name: artilleryio/artillery:latest
    entrypoint: [""]
  script: |
    mkdir reports
    /home/node/artillery/bin/artillery run --output reports/report.json tests/performance/socket-io.yml
  artifacts:
    paths:
      - reports
