pipeline {
    agent {
        docker {
            image 'artilleryio/artillery:latest'
            args '-u root:root -i --entrypoint='
        }
    }

    triggers {
        cron('0 0 * * *')
    }

    stages {
        stage('Load Test') {
            steps {
                sh 'mkdir reports'
                sh '/home/node/artillery/bin/artillery run --output reports/report.json tests/performance/socket-io.yml'
            }
        }
    }

    post {
        success {
            archiveArtifacts 'reports/*'
        }
    }
}
