apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-browser
  labels:
    app: movie-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-browser
  template:
    metadata:
      labels:
        app: movie-browser
    spec:
      containers:
        - name: nginx
          image: ghcr.io/artilleryio/movie-browser-test-endpoints:latest
          ports:
            - containerPort: 3001
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /healthz
              httpHeaders:
                - name: Host
                  value: myapplication1.com
              port: 3001
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie-browser
  name: movie-browser-service
  namespace: default
spec:
  ports:
    - name: nginx-http-port
      port: 80
      targetPort: 3001
  selector:
    app: movie-browser
  sessionAffinity: None
  type: ClusterIP
