THIS_FILE := $(lastword $(MAKEFILE_LIST))

# VERSION defines the project version for the bundle.
# Update this value when you upgrade the version of your project.
# To re-generate a bundle for another specific version without changing the standard setup, you can:
# - use the VERSION as arg of the bundle target (e.g make bundle VERSION=0.0.2)
# - use environment variables to overwrite this value (e.g export VERSION=0.0.2)
VERSION ?= latest

IMAGE_REPO_OWNER ?= artilleryio

IMAGE_PLATFORM ?= linux/amd64
COMMIT_TAG := $(shell git log -1 --pretty=%H)
APP_IMAGE_NAME ?= movie-browser-test-endpoints

# Image URL to use all building/pushing image targets
APP_IMG ?= $(IMAGE_REPO_OWNER)/$(APP_IMAGE_NAME):$(VERSION)


# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec

all: help

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk commands is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Build API docker image

docker-build: ## Build docker image with the api.
	docker build -f Dockerfile --platform "${IMAGE_PLATFORM}" -t "${APP_IMAGE_NAME}:${COMMIT_TAG}" .
	docker tag "${APP_IMAGE_NAME}:${COMMIT_TAG}" ${APP_IMG}

docker-push: ## Push docker image with the api.
	docker push ${APP_IMG}
