name: test-websockets

on:
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./examples/websockets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run test.yml
