name: gh-action-test
on:
  push:
    branches: [feat/github-actions]
jobs:
  action-test:
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Action test
        id: loadtest
        uses: ./packages/artillery-github-action
        with:
          test: ./packages/artillery-github-action/test.yml

      - name: Output test
        run: echo "${{ steps.loadtest.outputs.report }}"
